//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.20 at 04:29:55 PM CST 
//


package https.github_com.gerardort95;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for location_area_encounters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="location_area_encounters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="location_area" type="{https://github.com/GerardoRT95}location_area"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "location_area_encounters", propOrder = {
    "locationArea"
})
public class LocationAreaEncounters {

    @XmlElement(name = "location_area", required = true)
    protected LocationArea locationArea;

    /**
     * Gets the value of the locationArea property.
     * 
     * @return
     *     possible object is
     *     {@link LocationArea }
     *     
     */
    public LocationArea getLocationArea() {
        return locationArea;
    }

    /**
     * Sets the value of the locationArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationArea }
     *     
     */
    public void setLocationArea(LocationArea value) {
        this.locationArea = value;
    }

}
