//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.20 at 04:29:55 PM CST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "https://github.com/GerardoRT95", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.github_com.gerardort95;
